### ISSUE TITLE
Jupyter notebook kernel crashed when running dicom2nifti.convert_directory method

### ISSUE THREAD

**Issue by Yanglinjun1** [icometrix/dicom2nifti#131]
I am trying to convert DICOM series into nifti volumes by using the dicom2nifti.convert_directory() and dicom2nifti.dicom_series_to_nifti()  However, both methods cause the kernel to crash. I also tried to copy and paste codes in a python file and run it, and still couldn't convert the files. The following is what I got when running the codes in jupyter kernel:

`Canceled future for execute_request message before replies were done
The Kernel crashed while executing code in the the current cell or a previous cell. Please review the code in the cell(s) to identify a possible cause of the failure. Click [here](https://aka.ms/vscodeJupyterKernelCrash) for more info. View Jupyter [log](command:jupyter.viewOutput) for further details.`

Could you help me solve it?

**Comment by abrys** [comment]
Could you provide any more information.
- Operating system
- Available memory
- Python version
- Dicom2nifti version
- Type of dicom data and size of the dicom data on disk

I would assume a crash of the kernel is actually caused by an external source and not the code itself. For example not enough memory to do the conversion, a bad/corrupted library being used, ...
I would need some more info that this to be able to help
