### ISSUE TITLE
Is it possible to convert straight to .nii instead of .nii.gz?

### ISSUE THREAD

**Issue by TheGormlessGit** [icometrix/dicom2nifti#52]
I have a script to rename the .nii.gz files after conversion, but these names do not carry over if I unzip the files with 7-zip, which needs to be done for use with Vivoquant/ 

There doesn't seem to be a way to unzip the .nii.gz files directly with python, which would solve the problem, and stopping the script midway to have the user unzip everything wouldn't be ideal.

With that in mind, I would like to ask please whether it's possible to set dicom2nifti to convert DICOMs straight into .nii files? Or, alternatively, whether such functionality could be added in the future?

Thank you for your time.

**Comment by abrys** [comment]
Can you please provide some more information:
- Are you running from command line or from the python interface?
It should be possible to add this functionality in the near future.

**Comment by TheGormlessGit** [comment]
Apologies for not already mentioning that. I'm running from the python interface.

I have actually solved this problem now. I've managed to call 7-zip as a subprocess and it seems to work fine, but I think that having the functionality in-built would still be best just for ease of use.

At the risk of sounding a bit cheeky, would it please be possible to add a 'disable logging' option in the future? I have removed a lot of the logging from the module's .py files myself, but again, I think others would find it useful too as the module is quite 'noisy' in the command prompt and can drown out other printed lines if it's part of a larger script.

Regardless, thanks for the response and I want you to know that I'm very happy with the program even in its current state. It's done everything I've wanted to without much of an issue. I appreciate your work.

**Comment by abrys** [comment]
About the logging there is not need for a specific option.
As all is done using the default python logging all that needs to be done is configure the correct level of logging you want for the specific module. Otherwise it will inherit the global logging level.

So if you want to surpress more do:
import logging 
logging.getLogger('dicom2nifti').setLevel(logging.WARNING)

For more information see:
https://docs.python.org/2/library/logging.html#levels

**Comment by abrys** [comment]
Was looking into implementing this and it turns out that I had foreseen this from the beginning.
The dicom2nifti.convert_directory actually has an optional parameter 'compression'.
So doing the following should do the trick
`dicom2nifti.convert_directory(dicom_directory, output_folder, compression=False)`
