### ISSUE TITLE
value change to array data

### ISSUE THREAD

**Issue by bkonk** [icometrix/dicom2nifti#87]
Hi,

I've been using the convert series command with reorient_nifti=True to convert several of my dicom series. I've noticed that after doing this, my nibfile.get_fdata() pixel values are -1024 my initial dcmfile.pixel_array values. This may be the same issue as #83

```
print(np.amin(dcmfile.pixel_array), ' : ', np.amax(dcmfile.pixel_array))
0 : 2325
nib_array = nibfile.get_fdata()
print(np.amin(nib_array), ' : ', np.amax(nib_array))
-1024.0 : 1301.0
```

Probably relevant are:
```
dcmfile.RescaleSlope = 1
dcmfile.RescaleIntercept = -1024

```
which in the converted nib file seem absent:

```
nibfile.header['scl_inter'] = nan
nibfile.header['scl_slope'] = nan
```

Is there something in the conversion process that changes pixel values and then throws away slope and intercept tags?

Thanks

**Comment by abrys** [comment]
This is expected behaviour as dicom2nifti applies the rescaling to the image data instead of setting the them on the headers.
This is a conscious decision to avoid issues with software/tools that do not take it into account correctly.
We should however set scl_inter to 0 and scl_slope to 1.
We will do that in the next release.

**Comment by abrys** [comment]
Will be included in the next release
