### ISSUE TITLE
How to handle missing mosaic tags in Siemens dicoms

### ISSUE THREAD

**Issue by Kai-Chen** [icometrix/dicom2nifti#91]
Hi,

I have a question about this line in the function `_mosaic_to_block`

https://github.com/icometrix/dicom2nifti/blob/82840c1a9dc4c2598df1ff49e4283a0f39433216/dicom2nifti/convert_siemens.py#L462

In quite a few Siemens scans, this tag value is missing, which prevents conversion to nifti.

From the code it looks like it's looking for dimension information, and what is the dimension of?
And in cases of missing tag values, is there another tag where the information may be retrieved and restored?

Thanks!

**Comment by abrys** [comment]
Hello,

This is looking for the size of an individual "tile" in the mosaic, in order to know where to take the data to reconstruct the individual "timepoint/direction" volume.
If this data is missing on of two things probably happend.
-  The data was anonymised and all private tags where removed not taking into account that some are needed for reconstruction [MOST LIKELY REASON]
- The data is a format that is unknown/unseen to us and stores this information elsewhere

If it would be possible/allowed to share an example I could take a look at it however in the first case there is probably not very much we would be able to do.
If you know the source of the original data and it was anonymised it is worth checking if the original data did contain this dicom tag.

Kind regards,
Arne

**Comment by Kai-Chen** [comment]
Thanks for the quick response, Arne!

Yes, the data was anonymized before being shared with us.
There are other headers that we found that contain the dimensions (such as in the optional `Acquisition Matrix` and the Siemens CSA Header.
Do you think these tag values are reliable?

I do have 1 data set that I can share -- it's about 100 MB in size.
What's the best way to send it to you if you are interested?

**Comment by Kai-Chen** [comment]
I'm going to close this one, as we've found an acceptable solution.
The fix is very situation-specific and is also just a tie-over, so I doubt there's much value in sending it as a patch.
Thanks for the help!
